# Generated by Django 5.1.2 on 2024-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apps',
            options={'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Sub Category'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Category'},
        ),
        migrations.AddField(
            model_name='apps',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
